<a href="https://colab.research.google.com/github/cpti372/study_ml/blob/master/numpy_%EC%A0%95%EB%A6%AC_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
np.array(range(5))
np.linspace(0,10,11)
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [5]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [6]:
np.zeros((1,3))


array([[0., 0., 0.]])

In [8]:
np.ones((3,3))
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [14]:
b=np.array(([1,2,3],[4,5,6],[7,8,9]))
b.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

스칼라 곱...

In [15]:
a=np.array((5,6,7))
b=np.array((6,6,6))
a.dot(b)

108

In [16]:
np.dot(a,b)

108

In [17]:
c=np.array(([1,2,3],[4,5,6],[7,8,9]))
cT=c.T
c.dot(a)

array([ 38,  92, 146])

In [18]:
c[0].dot(a)

38

In [19]:
c[1].dot(a)

92

In [20]:
c[2].dot(a)

146

In [21]:
a.dot(c)

array([ 78,  96, 114])

In [22]:
a.doc(cT[0])

AttributeError: ignored

In [23]:
a.dot(cT[0])

78

In [24]:
x=np.random.randint(0,10,size=(3,3))

In [25]:
x

array([[3, 6, 0],
       [7, 5, 6],
       [8, 5, 1]])

In [26]:
np.sort(x,axis=1)

array([[0, 3, 6],
       [5, 6, 7],
       [1, 5, 8]])

In [27]:
np.sort(x,axis=0)

array([[3, 5, 0],
       [7, 5, 1],
       [8, 6, 6]])

In [28]:
a=np.arnage(1,11,1)

AttributeError: ignored

In [29]:
a=np.arange(1,11,1)
a
a.reshape=2,5

AttributeError: ignored

In [30]:
a=np.arange(1,11,1)

In [31]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a.shape=2,5

In [33]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
a.shape=5,-1

In [35]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [41]:
b=a.reshape(2,5)

In [42]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
x=np.random.rand(10)

In [44]:
x

array([0.43506377, 0.87204676, 0.16449938, 0.92551936, 0.77136802,
       0.3474569 , 0.97718604, 0.72373766, 0.39111328, 0.91087502])

In [45]:
x=np.random.randint(0,10,size=(1,10))

In [46]:
x

array([[5, 1, 2, 9, 6, 0, 6, 4, 3, 4]])

In [47]:
np.where(x<5,0,1)

array([[1, 0, 0, 1, 1, 0, 1, 0, 0, 0]])

In [48]:
a_list=[3,5,7]
a_mat=np.matrix(a_list)

In [49]:
a_mat

matrix([[3, 5, 7]])

In [50]:
c_mat.argsort(axis=0)

NameError: ignored

In [51]:
a_mat.argsort(axis=0)

matrix([[0, 0, 0]])

In [52]:
a_mat.argsort(axis=1)

matrix([[0, 1, 2]])

In [53]:
from scipy import constants as C

In [54]:
C.pi

3.141592653589793

In [55]:
C.golden

1.618033988749895

In [56]:
C.c

299792458.0

In [57]:
C.h

6.62607015e-34

In [58]:
C,mile

NameError: ignored

In [59]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [60]:
import scipy.signal

In [62]:
scipy.signal.convolve(x,y)

array([ 4, 13, 28, 27, 18])

AttributeError: ignored